test:
  image: "python:3.12"
  before_script:
    - pip install --upgrade pip setuptools wheel
    - pip install -e .[dev] --default-timeout=180
    - apt-get update && apt-get install -yq --no-install-recommends nodejs npm default-jdk
    - npm install -g less
    - cd elixir_dcp/static/vendor
    - npm ci
  script:
    - cd ../../.. && pwd
    - cp elixir_dcp/settings.py.template elixir_dcp/settings.py
    - export ELIXIR_DCP_ENV='test'
    - pytest --cov=elixir_dcp --cov-report=term-missing
    - coverage report -m

include:
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: SAST.gitlab-ci.yml
sast:
  tags:
      - privileged
dependency_scanning:
  tags:
      - privileged
services:
- name: docker:stable-dind
  command: ["--mtu=1458"]
