image: "python:3.7"

before_script:
  - pip install -e .  --default-timeout=180
  - pip install coverage
  - apt update && apt install -yq --no-install-recommends nodejs npm openjdk-11-jdk
  - npm install -g less
  - cd elixir_dcp/static/vendor
  - npm ci

test:
  script:
    - cd ../..
    - cp elixir_dcp/settings.py.template elixir_dcp/settings.py
    - export ELIXIR_DCP_ENV='test'
    - coverage run setup.py test
    - coverage report -m

include:
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: SAST.gitlab-ci.yml
sast:
  tags:
      - privileged
dependency_scanning:
  tags:
      - privileged
services:
- name: docker:stable-dind
  command: ["--mtu=1458"]
