services:
  postgres:
    image: postgres:16-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: elixirdcp
      POSTGRES_PASSWORD: elixirdcp
      POSTGRES_DB: elixirdcp
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U elixirdcp"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: