site_name: Data Submission System (DSS)
theme:
  name: material
  palette:
      - scheme: default
        primary: deep green
        accent: blue grey
        toggle:
          icon: material/weather-night
          name: Switch to dark mode
      - scheme: slate
        primary: orange
        accent: blue
        toggle:
          icon: material/weather-sunny
          name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.details  
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search
  - mermaid2


nav:
  - Home: overview.md
  - User Guide:
      - Getting Started: user-guide.md/getting-started.md
      - Managing Submissions: user-guide.md/managing-submissions.md
      - Roles & Permissions: user-guide.md/roles.md
      - Submission States: user-guide.md/submission-states.md
      - Notifications: user-guide.md/notifications.md
  - Technical Documentation:
      - Authentication: technical-documentation/authentication.md
      - UI: technical-documentation/ui.md
      - Architecture & Design:
          - System Data Model: technical-documentation/architecture-and-design/system-data-model.md
          - Use Cases: technical-documentation/architecture-and-design/use-cases/use-cases.md
          - Sequence Diagram: technical-documentation/architecture-and-design/sequence-diagram.md
          - Components: technical-documentation/architecture-and-design/components/components.md
          - Scenarios: technical-documentation/architecture-and-design/scenarios.md
  - Development:
      - Development Guide: development/development.md
  - Metadata:
      - Form Metadata Model: form-metadata-model/form-metadata-model.md


