site_name: Data Submission System (DSS)
theme:
  name: material
  palette:
      - scheme: default
        primary: deep green
        accent: blue grey
        toggle:
          icon: material/weather-night
          name: Switch to dark mode
      - scheme: slate
        primary: orange
        accent: blue
        toggle:
          icon: material/weather-sunny
          name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.details  
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search
  - mermaid2


nav:
  - Home: overview.md
  - Technical design:
      - Use Cases: use_cases.md
      - Roles & Permissions: roles.md
      - Submission states: submission_states.md
      - Authentication & Access:
          - Authentication: docs/authentication.md
      - Notifications: 
  - Submission System:
      - System Overview: submission-system_specs.md
      - Scenarios: scenarios.md
      - Technical & Design:
          - Naming & Roles: submission-system_specs.md#define-who-is-provider-submit...
          - System Differences: submission-system_specs.md#how-this-system-differs-from-systems-used-for-other-sumbmissions-daisy-eln-platforms-ibridges-yoda-
          - Technical TODOs: submission-system_specs.md#todo
          - Data Model Entities: USER_WORKFLOWS.md#data-model-key-entities
          - Implementation Notes: USER_WORKFLOWS.md#technical-implementation-notes


