START_UP_DATA = {'ga4gh_codes': [['NRES', 'no restrictions', 'No restrictions on data use.'],
                                 ['GRU(CC)', 'general research use and clinical care',
                                  'For health/medical/biomedical purposes and other biological research, including the study of population origins or ancestry.'],
                                 ['HMB(CC)', 'health/medical/biomedical research and clinical care',
                                  'Use of the data is limited to health/medical/biomedical purposes, does not include the study of population origins or ancestry.'],
                                 ['DS-[XX](CC)', 'disease-specific research and clinical care.',
                                  'Use of the data must be related to [disease].'],
                                 ['POA', 'population origins/ancestry research',
                                  'Use of the data is limited to the study of population origins or ancestry.'],
                                 ['RS-[XX]', 'other research-specific restrictions',
                                  'Use of the data is limited to studies of [research type] (e.g., pediatric research).'],
                                 ['RUO', 'research use only',
                                  'Use of data is limited to research purposes (e.g., does not include its use in clinical care).'],
                                 ['NMDS', 'no \"general methods\" research',
                                  'Use of the data includes methods development research (e.g., development of software or algorithms) ONLY within the bounds of other data use limitations.'],
                                 ['GSO', 'genetic studies only',
                                  'Use of the data is limited to genetic studies only (i.e., no research using only the phenotype data).'],
                                 ['NPU', 'not-for-profit use only',
                                  'Use of the data is limited to not-for-profit organizations.'],
                                 ['PUB', 'publication required',
                                  'Requestor agrees to make results of studies using the data available to the larger scientific community.'],
                                 ['COL-[XX]', 'collaboration required',
                                  'Requestor must agree to collaboration with the primary study investigator(s).'],
                                 ['RTN', 'return data to database/resource',
                                  'Requestor must return derived/enriched data to the database/resource.'],
                                 ['IRB', 'ethics approval required',
                                  'Requestor must provide documentation of local IRB/REC approval.'],
                                 ['GS-[XX]', 'geographical restrictions',
                                  'Use of the data is limited to within [geographic region].'],
                                 ['MOR-[XX]', 'publication moratorium/embargo',
                                  'Requestor agrees not to publish results of studies until [date].'],
                                 ['TS-[XX]', 'time limits on use', 'Use of data is approved for [x months].'],
                                 ['US', 'user-specific restrictions',
                                  'Use of data is limited to use by approved users.'],
                                 ['PS', 'project-specific restrictions',
                                  'Use of data is limited to use within an approved project.'],
                                 ['IS', 'institution-specific restrictions',
                                  'Use of data is limited to use within an approved institution.']],
                 'contact_types': ['PI', 'Researcher', 'Data Manager', 'Data Protection Officer',
                                   'Legal Representative', 'Other'],
                 'names_roles': ['data_provider', 'admin'],
                 'size_categories': [['elx_s', 'Less than 10GB'],
                                     ['elx_m', 'Between 10 and 100GB'],
                                     ['elx_l', 'Greater than 100 GB']],
                 'data_types': [
                     "Omics_data",
                     "Genotype_data",
                     "Whole_genome_sequencing",
                     "Exome_sequencing",
                     "Genomics_variant_array",
                     "RNASeq",
                     "Genetic_and_derived_genetic_data",
                     "Transcriptome_array",
                     "Methylation_array",
                     "MicroRNA_array",
                     "Metabolomics",
                     "Metagenomics",
                     "Proteomics",
                     "Other_omics_data",
                     "Clinical_Imaging",
                     "Cell_Imaging",
                     "Human_subject_data",
                     "Clinical_data",
                     "Lifestyle_data",
                     "Socio_Economic_Data",
                     "Environmental_Data",
                     "Other_Phenotype_data",
                     "Other"
                 ],
                 'study_types': [
                     "Observational",
                     "Interventional",
                     "Expanded_Access",
                     "Longitudinal_Cohort",
                     "Cross_Sectional",
                     "Case_Control",
                     "Case_Set",
                     "Control_Set",
                     "Parent_Offspring",
                     "Unrelated_Individuals",
                     "Sibling_Pairs",
                     "Family",
                     "Pedigree",
                     "Preclinical_Trial",
                     "Clinical_Trial",
                     "Meta_Analysis",
                     "Prospective",
                     "Retrospective",
                     "Phase_I",
                     "Phase_II",
                     "Phase_III",
                     "Phase_IV",
                     "Single_Group",
                     "Parallel",
                     "Cross_Over",
                     "Factorial",
                     "Randomized",
                     "Blind",
                     "Controlled",
                     "Open",
                     "Single_Blind",
                     "Double_Blind"
                 ],
                 'collab_institutions': ['Max Planck Society',
                                         'Michael J. Fox Foundation',
                                         'Wellcome Sanger Institute',
                                         'National Institutes of Health (NIH)',
                                         'Erasmus University Medical Center (Erasmus MC)',
                                         'University of Lübeck',
                                         'Newcastle University',
                                         'University of Tübingen',
                                         'Paracelsus-Elena-Klinik Kassel',
                                         'University Hospital Cologne',
                                         'Murdoch Children\'s Research Institute (MCRI)',
                                         'University of Luxembourg',
                                         'Cologne Center for Genomics',
                                         'University Clinic Bonn',
                                         'Hospital Erasmus Brussels',
                                         'Royal College of Surgeons in Ireland',
                                         'Broad Institute',
                                         'European Molecular Biology Laboratory (EMBL)',
                                         'Hospital Erasmus Brussels',
                                         'Duke University Columbia',
                                         'University of Eastern Finland',
                                         'University of Melbourne',
                                         'Children\'s Hospital of Philadelphia',
                                         'Brazilian institute of Neuroscience',
                                         'Charité Clinic Berlin'],
                 'collab_pis': ['Reinhard Schneider',
                                'Enrico Glaab',
                                'Chemical Biology',
                                'Rudi Balling',
                                'Antonio del Sol',
                                'Jens Schwamborn',
                                'Pauyl Wilmes',
                                'Emma Schymanski',
                                'Ines Thiele',
                                'Rudi Balling',
                                'Jorge Goncalves',
                                'Rejko Krüger',
                                'Jochen Schneider',
                                'Anne Grünewald',
                                'Michel Mittelbronn',
                                'Alexander Skupin',
                                'Roland Krause',
                                'Patrick May',
                                'Carole Linster']
                 }
