"""Add personal data workflow fields to dataset

Revision ID: 2b7384554e38
Revises: e707d2bb7e55
Create Date: 2026-01-14 17:06:40.699682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b7384554e38'
down_revision = 'e707d2bb7e55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission_dataset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contains_personal_data', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('data_processing_type', sa.String(), nullable=True))
        batch_op.alter_column('de_identification_type_code',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission_dataset', schema=None) as batch_op:
        batch_op.alter_column('de_identification_type_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('data_processing_type')
        batch_op.drop_column('contains_personal_data')

    # ### end Alembic commands ###
