"""Initial migration with all models

Revision ID: 75ddbd8e40cf
Revises:
Create Date: 2025-11-24 09:29:07.524976

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "75ddbd8e40cf"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "consent_status",
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("code"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "contact_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "deidentification_type",
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("code"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "email_notification",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("subject", sa.String(), nullable=False),
        sa.Column("sender", sa.String(), nullable=False),
        sa.Column("recipients_json", sa.String(), nullable=False),
        sa.Column("text_body", sa.String(), nullable=False),
        sa.Column("html_body", sa.String(), nullable=False),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "legalbasis_type",
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("code"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=True),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "subject_category",
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("code"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "submission_scope",
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("code"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("elixir_sub_id", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("phone_no", sa.String(), nullable=True),
        sa.Column("addr_line1", sa.String(), nullable=True),
        sa.Column("addr_line2", sa.String(), nullable=True),
        sa.Column("institution_accession", sa.String(), nullable=True),
        sa.Column("institution_division", sa.String(), nullable=True),
        sa.Column("active_user", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("elixir_sub_id"),
    )
    op.create_table(
        "submissions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ref_name", sa.String(length=45), nullable=False),
        sa.Column("title", sa.String(length=75), nullable=False),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column("finalised_on", sa.DateTime(), nullable=True),
        sa.Column(
            "current_status",
            sa.Enum(
                "draft",
                "metadata_submission",
                "metadata_approval",
                "data_upload",
                "data_approval",
                "completed",
                name="submissionstatusenum",
            ),
            nullable=False,
        ),
        sa.Column("exported", sa.Boolean(), nullable=False),
        sa.Column("institution_accession", sa.String(), nullable=True),
        sa.Column("submission_scope_code", sa.String(), nullable=False),
        sa.Column("local_custodians_json", sa.String(), nullable=True),
        sa.Column("local_project_name", sa.String(), nullable=True),
        sa.Column("notes", sa.String(length=250), nullable=True),
        sa.ForeignKeyConstraint(
            ["submission_scope_code"],
            ["submission_scope.code"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("submissions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_submissions_ref_name"), ["ref_name"], unique=True
        )

    op.create_table(
        "users_roles",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("assigned_on", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "role_id"),
    )
    op.create_table(
        "submission_access",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("submission_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("access_granted_on", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["submission_id"], ["submissions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("submission_access", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_submission_access_submission_id"),
            ["submission_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_submission_access_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "submission_attachments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("submission_id", sa.Integer(), nullable=False),
        sa.Column("note", sa.String(), nullable=False),
        sa.Column("folder_name", sa.String(), nullable=False),
        sa.Column("file_names", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["submission_id"], ["submissions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("submission_attachments", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_submission_attachments_submission_id"),
            ["submission_id"],
            unique=False,
        )

    op.create_table(
        "submission_message",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("submission_id", sa.Integer(), nullable=False),
        sa.Column("created_on", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sender_user_id", sa.Integer(), nullable=False),
        sa.Column("message_text", sa.String(), nullable=False),
        sa.Column("message_type", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["sender_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"], ["submissions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("submission_message", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_submission_message_sender_user_id"),
            ["sender_user_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_submission_message_submission_id"),
            ["submission_id"],
            unique=False,
        )

    op.create_table(
        "submission_study",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("submission_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("website", sa.String(), nullable=True),
        sa.Column("ethics_approval_exists", sa.Boolean(), nullable=False),
        sa.Column("ethics_approval_no", sa.String(), nullable=True),
        sa.Column("study_types_json", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["submission_id"], ["submissions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("submission_study", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_submission_study_submission_id"),
            ["submission_id"],
            unique=False,
        )

    op.create_table(
        "contacts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("firstname", sa.String(), nullable=False),
        sa.Column("lastname", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("address", sa.String(), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("study_id", sa.Integer(), nullable=True),
        sa.Column("submission_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["contact_types.id"],
        ),
        sa.ForeignKeyConstraint(
            ["study_id"], ["submission_study.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"], ["submissions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("contacts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_contacts_category_id"), ["category_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_contacts_study_id"), ["study_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_contacts_submission_id"), ["submission_id"], unique=False
        )

    op.create_table(
        "submission_dataset",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("external_id", sa.String(length=20), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("submission_id", sa.Integer(), nullable=False),
        sa.Column("study_id", sa.Integer(), nullable=True),
        sa.Column("gdpr_datatypes_json", sa.String(), nullable=False),
        sa.Column("gdpr_datatypes_notes", sa.String(), nullable=True),
        sa.Column("sci_datatypes_json", sa.String(), nullable=False),
        sa.Column("sci_datatypes_notes", sa.String(), nullable=True),
        sa.Column("de_identification_type_code", sa.String(), nullable=False),
        sa.Column("has_samples", sa.Boolean(), nullable=False),
        sa.Column("samples_notes", sa.String(), nullable=True),
        sa.Column("legal_basis_collection_std_code", sa.String(), nullable=False),
        sa.Column("legal_basis_sharing_std_code", sa.String(), nullable=False),
        sa.Column("legal_basis_collection_spec_code", sa.String(), nullable=False),
        sa.Column("legal_basis_sharing_spec_code", sa.String(), nullable=False),
        sa.Column("legal_basis_notes", sa.String(), nullable=True),
        sa.Column("subject_category_code", sa.String(), nullable=False),
        sa.Column("has_special_subjects", sa.Boolean(), nullable=False),
        sa.Column("special_subjects_notes", sa.String(), nullable=True),
        sa.Column("consent_status_code", sa.String(), nullable=False),
        sa.Column("consent_notes", sa.String(), nullable=True),
        sa.Column("restriction_rs", sa.Boolean(), nullable=False),
        sa.Column("restriction_rs_notes", sa.String(), nullable=True),
        sa.Column("restriction_gs", sa.Boolean(), nullable=False),
        sa.Column("restriction_gs_notes", sa.String(), nullable=True),
        sa.Column("restriction_us", sa.Boolean(), nullable=False),
        sa.Column("restriction_us_notes", sa.String(), nullable=True),
        sa.Column("restriction_pub", sa.Boolean(), nullable=False),
        sa.Column("restriction_pub_notes", sa.String(), nullable=True),
        sa.Column("restriction_ts", sa.Boolean(), nullable=False),
        sa.Column("restriction_ts_notes", sa.String(), nullable=True),
        sa.Column("restriction_ps", sa.Boolean(), nullable=False),
        sa.Column("restriction_ps_notes", sa.String(), nullable=True),
        sa.Column("restriction_ts_lcsb", sa.Boolean(), nullable=False),
        sa.Column("restriction_ts_lcsb_notes", sa.String(), nullable=True),
        sa.Column("restriction_rtn", sa.Boolean(), nullable=False),
        sa.Column("restriction_rtn_notes", sa.String(), nullable=True),
        sa.Column("restriction_other_notes", sa.String(), nullable=True),
        sa.Column("access_form_required", sa.Boolean(), nullable=False),
        sa.Column("dac_approval_required", sa.Boolean(), nullable=False),
        sa.Column("dac_approval_notes", sa.String(), nullable=True),
        sa.Column("restriction_ip", sa.Boolean(), nullable=False),
        sa.Column("restriction_ip_notes", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["consent_status_code"],
            ["consent_status.code"],
        ),
        sa.ForeignKeyConstraint(
            ["de_identification_type_code"],
            ["deidentification_type.code"],
        ),
        sa.ForeignKeyConstraint(
            ["legal_basis_collection_spec_code"],
            ["legalbasis_type.code"],
        ),
        sa.ForeignKeyConstraint(
            ["legal_basis_collection_std_code"],
            ["legalbasis_type.code"],
        ),
        sa.ForeignKeyConstraint(
            ["legal_basis_sharing_spec_code"],
            ["legalbasis_type.code"],
        ),
        sa.ForeignKeyConstraint(
            ["legal_basis_sharing_std_code"],
            ["legalbasis_type.code"],
        ),
        sa.ForeignKeyConstraint(
            ["study_id"], ["submission_study.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["subject_category_code"],
            ["subject_category.code"],
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"], ["submissions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_id"),
    )
    with op.batch_alter_table("submission_dataset", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_submission_dataset_study_id"), ["study_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_submission_dataset_submission_id"),
            ["submission_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("submission_dataset", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_submission_dataset_submission_id"))
        batch_op.drop_index(batch_op.f("ix_submission_dataset_study_id"))

    op.drop_table("submission_dataset")
    with op.batch_alter_table("contacts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_contacts_submission_id"))
        batch_op.drop_index(batch_op.f("ix_contacts_study_id"))
        batch_op.drop_index(batch_op.f("ix_contacts_category_id"))

    op.drop_table("contacts")
    with op.batch_alter_table("submission_study", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_submission_study_submission_id"))

    op.drop_table("submission_study")
    with op.batch_alter_table("submission_message", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_submission_message_submission_id"))
        batch_op.drop_index(batch_op.f("ix_submission_message_sender_user_id"))

    op.drop_table("submission_message")
    with op.batch_alter_table("submission_attachments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_submission_attachments_submission_id"))

    op.drop_table("submission_attachments")
    with op.batch_alter_table("submission_access", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_submission_access_user_id"))
        batch_op.drop_index(batch_op.f("ix_submission_access_submission_id"))

    op.drop_table("submission_access")
    op.drop_table("users_roles")
    with op.batch_alter_table("submissions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_submissions_ref_name"))

    op.drop_table("submissions")
    op.drop_table("users")
    op.drop_table("submission_scope")
    op.drop_table("subject_category")
    op.drop_table("roles")
    op.drop_table("legalbasis_type")
    op.drop_table("email_notification")
    op.drop_table("deidentification_type")
    op.drop_table("contact_types")
    op.drop_table("consent_status")
    # ### end Alembic commands ###
