"""Remove submission_scope and recipient lab

Revision ID: e707d2bb7e55
Revises: b3b0006e8f0b
Create Date: 2026-01-08 11:56:17.545825

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e707d2bb7e55"
down_revision = "b3b0006e8f0b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("submissions", schema=None) as batch_op:
        batch_op.drop_column("submission_scope_code")
    op.drop_table("submission_scope")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "submission_scope",
        sa.Column("code", sa.VARCHAR(), nullable=False),
        sa.Column("label", sa.VARCHAR(), nullable=False),
        sa.PrimaryKeyConstraint("code"),
        sa.UniqueConstraint("code"),
    )

    with op.batch_alter_table("submissions", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("submission_scope_code", sa.VARCHAR(), nullable=False)
        )
        batch_op.create_foreign_key(
            "fk_submissions_scope",
            "submission_scope",
            ["submission_scope_code"],
            ["code"],
        )

    # ### end Alembic commands ###
