START_UP_DATA = {
    "contact_types": [
        "Principal_Investigator",
        "Researcher",
        "Data_Manager",
        "Data_Protection_Officer",
        "Legal_Representative",
        "Other",
    ],
    "names_roles": ["data_steward", "admin", "user"],
    "deidentification_type": [["p", "Pseudonymised"], ["a", "Anonymised"]],
    "subject_category": [
        ["ca", "Cases"],
        ["co", "Controls"],
        ["ca_co", "Cases_and_Controls"],
    ],
    "consent_status": [["hm", "Homogeneous"], ["ht", "Heterogeneous"], ["dk", "Don't know"]],
    "legal_basis": [
        ["61a", "Consent (6.1(a))"],
        ["61b", "Performance of a contract to which the data subject is party (6.1(b))"],
        [
            "61c",
            "Compliance with a legal obligation to which the controller is subject (6.1(c))",
        ],
        ["61d", "Protection the vital interests of the data subject (6.1(d))"],
        ["61e", "Public interest (6.1(e))"],
        ["61f", "Legitimate interest (6.1(f))"],
    ],
    "submission_scope": [
        ["elu", "ELIXIR Luxembourg"],
        ["l_bc", "LCSB/Bioinformatics Core"],
        ["l_bmd", "LCSB/Biomedical Data Science"],
        ["l_chb", "LCSB/Chemical Biology"],
        ["l_cen", "LCSB/Clinical & Experimental Neuroscience"],
        ["l_ccb", "LCSB/Computational Biology"],
        ["l_dcb", "LCSB/Developmental & Cellular Biology"],
        ["l_esb", "LCSB/Eco-Systems Biology"],
        ["l_ec", "LCSB/Environmental Cheminformatics"],
        ["l_em", "LCSB/Enzymology & Metabolism"],
        ["l_en", "LCSB/Experimental Neurobiology"],
        ["l_ics", "LCSB/Integrative Cell Signalling"],
        ["l_in", "LCSB/Interventional Neuroscience"],
        ["l_mtr", "LCSB/Medical Translational Research"],
        ["l_mfn", "LCSB/Molecular & Functional Neurobiology"],
        ["l_np", "LCSB/Neuropathology"],
        ["l_sbc", "LCSB/Systems Biochemistry"],
        ["l_sc", "LCSB/Systems Control"],
    ],
    "gdpr_datatypes": (
        ("non_human", "Non-human data"),
        ("standard", "Standard personal data"),
        (
            "Special_category_sensitive_personal_data",
            (
                ("ethnic", "Racial or ethnic origin"),
                ("genetic", "Genetic data"),
                (
                    "biometric",
                    "Biometric data for the purpose of uniquely identifying a natural person",
                ),
                ("health", "Data concerning health"),
                ("sex", "Data concerning a natural person's sex life or sexual orientation"),
                ("criminal", "Data relating to criminal convictions and offences"),
                (
                    "other",
                    "Other special categories of data (e.g., molecular data that can give indication of a person's health)",
                ),
            ),
        ),
    ),
    "sci_datatypes": (
        (
            "Genotype_data",
            (
                ("Whole_genome_sequencing", "Whole genome sequencing"),
                ("Exome_sequencing", "Exome sequencing"),
                ("Genomics_variant_array", "Genomics variant array"),
                ("RNASeq", "RNASeq"),
                ("Single_Cell_RNAseq", "Single Cell RNAseq"),
            ),
        ),
        (
            "Genetic_and_derived_genetic_data",
            (
                ("Transcriptome_array", "Transcriptome array"),
                ("Methylation_array", "Methylation array"),
                ("MicroRNA_array", "MicroRNA array"),
                ("ChIP_seq", "ChIP-seq"),
                ("Metabolomics", "Metabolomics"),
                ("Metagenomics", "Metagenomics"),
                ("Metaproteomics", "Metaproteomics"),
                ("Metatranscriptomics", "Metatranscriptomics"),
                ("Proteomics", "Proteomics"),
            ),
        ),
        ("Other_omics_data", "Other omics data"),
        (
            "Imaging_data",
            (
                ("Clinical_imaging", "Clinical imaging"),
                ("Cell_imaging", "Cell imaging"),
                ("Other_imaging_data", "Other imaging data"),
            ),
        ),
        (
            "Human_subject_data",
            (
                ("Clinical_data", "Clinical data"),
                ("Lifestyle_data", "Lifestyle data"),
                ("Socio_Economic_data", "Socio Economic data"),
                ("Environmental_data", "Environmental data"),
                ("Ethnic_origin", "Ethnic origin"),
                ("Biometric_data", "Biometric data"),
                ("Other_Phenotype_data", "Other phenotype data"),
            ),
        ),
        ("Other", "Other"),
    ),
    "study_types": [
        "Observational",
        "Interventional",
        "Expanded_Access",
        "Longitudinal_Cohort",
        "Cross_Sectional",
        "Case_Control",
        "Case_Set",
        "Control_Set",
        "Parent_Offspring",
        "Unrelated_Individuals",
        "Sibling_Pairs",
        "Family",
        "Pedigree",
        "Preclinical_Trial",
        "Clinical_Trial",
        "Meta_Analysis",
        "Prospective",
        "Retrospective",
        "Phase_I",
        "Phase_II",
        "Phase_III",
        "Phase_IV",
        "Single_Group",
        "Parallel",
        "Cross_Over",
        "Factorial",
        "Randomized",
        "Blind",
        "Controlled",
        "Open",
        "Single_Blind",
        "Double_Blind",
    ],
    # Contact roles (optional preset values, though can also be free text)
    "contact_roles": [
        "Principal_Investigator",
        "Researcher",
        "Data_Manager",
        "Data_Protection_Officer",
        "Legal_Representative",
        "Other",
    ],
    # Yes/No/Don't know options (for fields with uncertain states)
    "yes_no_na": [
        "Yes",
        "No",
        "Don't know",
    ],
    "foreground_background": [
        "Background",
        "Results",
    ],
    "request_form": [
        "Additional form needed",
        "No additional form needed",
    ],
    "dac": [
        "DAC approval needed",
        "DAC approval not needed",
    ],
    # Species (NCBITaxon ontology) - starter values
    "species": [
        "Homo sapiens (NCBITaxon:9606)",
        "Mus musculus (NCBITaxon:10090)",
        "Rattus norvegicus (NCBITaxon:10116)",
        "Danio rerio (NCBITaxon:7955)",
        "Drosophila melanogaster (NCBITaxon:7227)",
    ],
    # Diseases (MONDO ontology) - starter values
    "diseases": [
        "Parkinson's disease (MONDO:0005180)",
        "Type II diabetes mellitus (MONDO:0005148)",
        "Alzheimer's disease (MONDO:0004975)",
        "Crohn's disease (MONDO:0005011)",
        "Breast cancer (MONDO:0007254)",
    ],
    # Sample sources (NCIt, EFO, UBERON ontologies) - starter values
    "sample_sources": [
        "Tissue sample",
        "Cell line",
        "Blood (UBERON:0000178)",
        "Brain (UBERON:0000955)",
        "Liver (UBERON:0002107)",
        "Saliva (UBERON:0001836)",
    ],
    "cohorts": [
        {
            "external_id": "ELU_C_1",
            "title": "LuxPARK",
            "ombudsman": ["Rejko Kr\u00fcger"],
            "comments": "HELP-PD will establish a state-of-the-art cohort project of patients with parkinsonism in Luxembourg to identify predictive and progression markers of the disease.  Thereby this project provides a unique infrastructure and resource for innovative clinical research in Luxembourg. The cohort program integrates an informative design (patient cohorts as well as risk cohorts in Phase II), a detailed neurological examination and structured assessment of epidemiological, neuropsychological and other clinical features, a comprehensive collection of biosamples and an integrated, anonymized data repository with web-based access. Initially, a cross-sectional assessment aimed at all diagnosed PD cases in Luxembourg will be performed, establishing a foundation for the PD registry. Subsequently, patients with PD will be followed up longitudinally.",
            "institutes": ["ELU_I_77", "ELU_I_9", "ELU_I_1", "ELU_I_79"],
        }
    ],
    "partners": [
        {
            "external_id": "ELU_I_1",
            "name": "Integrated Biobank of Luxembourg",
            "geo_category": "National",
            "sector_category": "PUBLIC",
            "is_clinical": False,
            "acronym": "IBBL",
        },
        {
            "external_id": "ELU_I_9",
            "name": "Centre Hospitalier de Luxembourg",
            "geo_category": "National",
            "sector_category": "PUBLIC",
            "is_clinical": True,
            "acronym": "CHL",
        },
        {
            "external_id": "ELU_I_77",
            "name": "Luxembourg Centre for Systems Biomedicine",
            "geo_category": "National",
            "sector_category": "PUBLIC",
            "is_clinical": False,
            "acronym": "LCSB",
        },
        {
            "external_id": "ELU_I_79",
            "name": "Luxembourg institute of health",
            "geo_category": "National",
            "sector_category": "PUBLIC",
            "is_clinical": False,
            "acronym": "Lih",
        },
    ],
    "projects": [
        {
            "external_id": "ELU_P_1",
            "name": "HELP-PD",
            "acronym": "HELP-PD",
        }
    ],
    "lcsb_pis": [
        "Reinhard Schneider",
        "Enrico Glaab",
        "Rudi Balling",
        "Antonio del Sol",
        "Jens Schwamborn",
        "Paul Wilmes",
        "Emma Schymanski",
        "Jorge Goncalves",
        "Rejko Krüger",
        "Jochen Schneider",
        "Anne Grünewald",
        "Michel Mittelbronn",
        "Alexander Skupin",
        "Frank Hertel",
        "Carole Linster",
    ],
    "dataset_types": [
        ["use_case_1", "Use case 1: Data received at LCSB but not hosted"],
        ["use_case_2", "Use case 2: Data received and hosted at LCSB for reuse"],
    ],
    "data_standards": [
        "CDISC",
        "MINSEQE",
        "NCIt",
        "EDAM",
        "OMOP",
        "FHIR",
        "HL7",
        "Other",
    ],
    "file_types": [
        "CSV (format:3752)",
        "TSV (format:3475)",
        "FASTQ (format:1930)",
        "BAM (format:2572)",
        "VCF (format:3016)",
        "JSON (format:3464)",
        "XML (format:2332)",
        "XLSX (format:3620)",
        "HDF5",
        "Parquet",
        "Other",
    ],
    "sample_types": [
        "blood",
        "plasma",
        "serum",
        "saliva",
        "urine",
        "tissue",
        "tumor tissue",
        "skin",
        "brain",
        "liver",
        "DNA",
        "RNA",
        "cells",
        "Other",
    ],
    "data_bg_or_result_types": [
        "Background",
        "Results",
    ],
}
