START_UP_DATA = {
    "contact_types": [
        "Principal_Investigator",
        "Researcher",
        "Data_Manager",
        "Data_Protection_Officer",
        "Legal_Representative",
        "Other",
    ],
    "names_roles": ["data_provider", "admin"],
    "deidentification_type": [["p", "Pseudonymized"], ["a", "Anonymized"]],
    "subject_category": [
        ["ca", "Cases"],
        ["co", "Controls"],
        ["ca_co", "Cases_and_Controls"],
    ],
    "consent_status": [["hm", "Homogeneous"], ["ht", "Heterogeneous"]],
    "legal_basis": [
        ["61a", "Consent (6.1(a))"],
        ["61b", "Performance of a contract to which the data subject is party(6.1(b))"],
        [
            "61c",
            "Compliance with a legal obligation to which the controller is subject (6.1(c))",
        ],
        ["61d", "Protection the vital interests of the data subject (6.1(d))"],
        ["61e", "Public interest (6.1(e))"],
        ["61f", "Legitimate interest (6.1(f))"],
    ],
    "submission_scope": [
        ["elu", "ELIXIR Luxembourg"],
        ["l_bc", "LCSB/Bioinformatics Core"],
        ["l_bmd", "LCSB/Biomedical Data Science"],
        ["l_chb", "LCSB/Chemical Biology"],
        ["l_cen", "LCSB/Clinical & Experimental Neuroscience"],
        ["l_ccb", "LCSB/Computational Biology"],
        ["l_dcb", "LCSB/Developmental & Cellular Biology"],
        ["l_esb", "LCSB/Eco-Systems Biology"],
        ["l_ec", "LCSB/Environmental Cheminformatics"],
        ["l_em", "LCSB/Enzymology & Metabolism"],
        ["l_en", "LCSB/Experimental Neurobiology"],
        ["l_ics", "LCSB/Integrative Cell Signalling"],
        ["l_in", "LCSB/Interventional Neuroscience"],
        ["l_mtr", "LCSB/Medical Translational Research"],
        ["l_mfn", "LCSB/Molecular & Functional Neurobiology"],
        ["l_np", "LCSB/Neuropathology"],
        ["l_sbc", "LCSB/Systems Biochemistry"],
        ["l_sc", "LCSB/Systems Control"],
    ],
    "gdpr_datatypes": (
        ("standard", "Standard personal data"),
        (
            "Special category (sensitive) personal data",
            (
                ("ethnic", "Racial or ethnic origin"),
                ("genetic", "Genetic data"),
                (
                    "biometric",
                    "Biometric data for the purpose of uniquely identifying a person",
                ),
                ("health", "Data concerning health"),
                ("sex", "Data concerning a person's sex life or sexual orientation"),
                ("criminal", "Data relating to criminal convictions and offences"),
                (
                    "other",
                    "Other special categories of data (e.g. molecular data that can give indication on a person's health)",
                ),
            ),
        ),
    ),
    "sci_datatypes": (
        ("Samples", "Samples"),
        (
            "Genotype_data",
            (
                ("Whole_genome_sequencing", "Whole_genome_sequencing"),
                ("Exome_sequencing", "Exome_sequencing"),
                ("Genomics_variant_array", "Genomics_variant_array"),
                ("RNASeq", "RNASeq"),
            ),
        ),
        (
            "Genetic_and_derived_genetic_data",
            (
                ("Transcriptome_array", "Transcriptome_array"),
                ("Methylation_array", "Methylation_array"),
                ("MicroRNA_array", "MicroRNA_array"),
                ("Metabolomics", "Metabolomics"),
                ("Proteomics", "Proteomics"),
                ("Other_omics_data", "Other_omics_data"),
            ),
        ),
        (
            "Imaging",
            (
                ("Clinical_Imaging", "Clinical_Imaging"),
                ("Cell_Imaging", "Cell_Imaging"),
                ("Other_Imaging", "Other_Imaging"),
            ),
        ),
        (
            "Human_subject_data",
            (
                ("Clinical_data", "Clinical_data"),
                ("Lifestyle_data", "Lifestyle_data"),
                ("Socio_Economic_Data", "Socio_Economic_Data"),
                ("Ethnic_origin", "Ethnic_origin"),
                ("Biometric_data", "Biometric_data"),
                ("Disease_status", "Disease_status"),
                ("Other_Phenotype_data", "Other_Phenotype_data"),
            ),
        ),
        ("Other", "Other"),
    ),
    "study_types": [
        "Observational",
        "Interventional",
        "Expanded_Access",
        "Longitudinal_Cohort",
        "Cross_Sectional",
        "Case_Control",
        "Case_Set",
        "Control_Set",
        "Parent_Offspring",
        "Unrelated_Individuals",
        "Sibling_Pairs",
        "Family",
        "Pedigree",
        "Preclinical_Trial",
        "Clinical_Trial",
        "Meta_Analysis",
        "Prospective",
        "Retrospective",
        "Phase_I",
        "Phase_II",
        "Phase_III",
        "Phase_IV",
        "Single_Group",
        "Parallel",
        "Cross_Over",
        "Factorial",
        "Randomized",
        "Blind",
        "Controlled",
        "Open",
        "Single_Blind",
        "Double_Blind",
    ],
    "cohorts": [
        {
            "external_id": "ELU_C_1",
            "title": "LuxPARK",
            "ombudsman": ["Rejko Kr\u00fcger"],
            "comments": "HELP-PD will establish a state-of-the-art cohort project of patients with parkinsonism in Luxembourg to identify predictive and progression markers of the disease.  Thereby this project provides a unique infrastructure and resource for innovative clinical research in Luxembourg. The cohort program integrates an informative design (patient cohorts as well as risk cohorts in Phase II), a detailed neurological examination and structured assessment of epidemiological, neuropsychological and other clinical features, a comprehensive collection of biosamples and an integrated, anonymized data repository with web-based access. Initially, a cross-sectional assessment aimed at all diagnosed PD cases in Luxembourg will be performed, establishing a foundation for the PD registry. Subsequently, patients with PD will be followed up longitudinally.",
            "institutes": ["ELU_I_77", "ELU_I_9", "ELU_I_1", "ELU_I_79"],
        }
    ],
    "partners": [
        {
            "external_id": "ELU_I_1",
            "name": "Integrated Biobank of Luxembourg",
            "geo_category": "National",
            "sector_category": "PUBLIC",
            "is_clinical": False,
            "acronym": "IBBL",
        },
        {
            "external_id": "ELU_I_9",
            "name": "Centre Hospitalier de Luxembourg",
            "geo_category": "National",
            "sector_category": "PUBLIC",
            "is_clinical": True,
            "acronym": "CHL",
        },
        {
            "external_id": "ELU_I_77",
            "name": "Luxembourg Centre for Systems Biomedicine",
            "geo_category": "National",
            "sector_category": "PUBLIC",
            "is_clinical": False,
            "acronym": "LCSB",
        },
        {
            "external_id": "ELU_I_79",
            "name": "Luxembourg institute of health",
            "geo_category": "National",
            "sector_category": "PUBLIC",
            "is_clinical": False,
            "acronym": "Lih",
        },
    ],
    "lcsb_pis": [
        "Reinhard Schneider",
        "Enrico Glaab",
        "Rudi Balling",
        "Antonio del Sol",
        "Jens Schwamborn",
        "Paul Wilmes",
        "Emma Schymanski",
        "Jorge Goncalves",
        "Rejko Krüger",
        "Jochen Schneider",
        "Anne Grünewald",
        "Michel Mittelbronn",
        "Alexander Skupin",
        "Frank Hertel",
        "Carole Linster",
    ],
}
